version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: always
    environment:
      - "DOMAIN=${DOMAIN}"
      - "CLIENT_MAX_BODY_SIZE=${CLIENT_MAX_BODY_SIZE}"
    depends_on:
      - wordpress
    expose:
      - 80
      - 443
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - nginx/logs:/var/log/nginx
      - wordpress-files:/var/www/html
    networks:
      - wordpress-site
  wordpress:
    image: wordpress:php8.0-fpm-alpine
    restart: always
    depends_on:
      - mariadb
      - redis
    expose:
      - 9000
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_NAME: ${WP_DB_NAME}
      WORDPRESS_DB_USER: ${WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_DB_PREFIX}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG:-false}
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_REDIS_HOST', 'redis' );
        define( 'WP_REDIS_PORT', 6379 );
        define( 'COMPRESS_CSS', true );
        define( 'COMPRESS_SCRIPTS', true );
        define( 'CONCATENATE_SCRIPTS', true );
        define( 'ENFORCE_GZIP', true );
        define( 'AUTOSAVE_INTERVAL', 120 );
        define( 'WP_POST_REVISIONS', 10);
        define( 'MEDIA_TRASH', true );
        define( 'EMPTY_TRASH_DAYS', 30 );
        define( 'IMAGE_EDIT_OVERWRITE', true );
        define( 'DISALLOW_FILE_EDIT', true );
    volumes:
      - wordpress-files:/var/www/html
      - ./wordpress/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - wordpress-site
  mariadb:
    image: mariadb:latest
    container_name: ${APP_NAME}-mariadb
    restart: always
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${WP_DB_NAME}
      MYSQL_USER: ${WP_DB_USER}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${WP_DB_ROOT_PASSWORD}
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - wordpress-site
  adminer:
    image: adminer:latest
    container_name: ${APP_NAME}-adminer
    restart: always
    depends_on:
      - mariadb
    expose:
      - 8080
    networks:
      - wordpress-site
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    image: redis:7.4-alpine
    container_name: ${APP_NAME}-redis
    restart: always
    expose:
      - 6379
    privileged: true
    volumes:
      - redis:/var/lib/redis
      - redis:/data
    networks:
      - wordpress-site
networks:
  name: wordpress-site
  external: true
